### ISSUE TITLE
Metaseo Migration Script in 3.0.2 broken

### ISSUE THREAD

**Issue by tobiasgraeber** [clickstorm/cs_seo#200]
Hi,

the migration script from metaseo to cs_seo in v3.0.2 is broken.
You already fixed that in the master, but there is no working release for TYPO3 8.7 yet and the master branch has alreade a TYPO3 9.4 dependency (composer) - so TYPO3 8.7 users (like me) does not have a chance to fix this bug.

**Could you please provide a new release for TYPO3 8.7 including your fixes from https://github.com/clickstorm/cs_seo/blob/master/Classes/Utility/DatabaseUtility.php ?**

The following is needed to fix the update part (for metaseo):

See:

https://github.com/clickstorm/cs_seo/blob/3x/class.ext_update.php#L157

Replace the method "migrateFields" by:

``
protected function migrateFields($fieldsToMigrate, $table)
    {

        foreach ($fieldsToMigrate as $oldField => $newField) {

            /** @var QueryBuilder $queryBuilder */
            $queryBuilder = GeneralUtility::makeInstance(ConnectionPool::class)
                ->getQueryBuilderForTable($table);

            $queryBuilder
                ->update($table, 'u')
                ->where(
                    $queryBuilder->expr()->orX(
                        $queryBuilder->expr()->eq($newField, $queryBuilder->createNamedParameter('', \PDO::PARAM_STR)),
                        $queryBuilder->expr()->isNull($newField)
                    )
                )
                ->set('u.' . $newField, $queryBuilder->quoteIdentifier('u.' . $oldField), false)->execute();
        }

    }
``

Thank you very much!

**Comment by mhirdes** [comment]
Hi the branch 3x is for TYPO3 8.7. I will fix this asp

**Comment by mhirdes** [comment]
It's fixed in the branch. Maybe you like to test?

**Comment by tobiasgraeber** [comment]
thanks but it does not work ...

`Uncaught Doctrine\DBAL\Driver\Mysqli\MysqliException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') OR (`tx_csseo_title` IS NULL)' at line 1 in ...vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\Mysqli\MysqliConnection.php:150
Stack trace:
#0 ...vendor\doctrine\dbal\lib\Doctrine\DBAL\Connection.php(1012): Doctrine\DBAL\Driver\Mysqli\MysqliConnection->exec('UPDATE `pages` ...')
#1 ...vendor\doctrine\dbal\lib\Doctrine\DBAL\Query\QueryBuilder.php(208): Doctrine\DBAL\Connection->executeUpdate('UPDATE `pages` ...', Array, Array)
#2 ...vendor\typo3\cms\typo3\sysext\core\Classes\Database\Query\QueryBuilder.php(181): Doctrine\DBAL\Query\QueryBuilder->execute()
#3 ...web\typo3conf\ext\cs_seo\class.ext_update.php(173): TYPO3\CMS\Core\Database\Query\QueryBuilder->execute()
#4 ...web\typo3con in ...vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\AbstractMySQLDriver.php on line 90`

I think you mixed something up now ...

use Clickstorm\CsSeo\Utility\DatabaseUtility; 
and method migrateFields() is missing...

is now used, before it was

use TYPO3\CMS\Extbase\Persistence\Generic\Query;

Just try the "update" process with a new choutout ov dev-3x -> it breaks with the error above ...

My file here: https://github.com/tobiasgraeber/cs_seo/blob/master/class.ext_update.php 

works...

Could you please have a deeper look and fix that? Thanks in advance!

**Comment by tobiasgraeber** [comment]
maybe re-open this issue also?

**Comment by mhirdes** [comment]
fixed it for the branch 3x

**Comment by tobiasgraeber** [comment]
Updated to latest dev-3x. Sorry but its still failing, with error message:

`
Oops, an error occurred!
An exception occurred while executing 'UPDATE `pages` `u` SET `u`.`tx_csseo_title` = ? WHERE (`tx_csseo_title` = ) OR (`tx_csseo_title` IS NULL)' with params [":dcValue1"]: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ') OR (`tx_csseo_title` IS NULL)' at line 1
`
