### ISSUE TITLE
Bug: Page results doesn't work with backend-CSP

### ISSUE THREAD

**Issue by SusiSorglos** [clickstorm/cs_seo#341]
The cs-seo backend-module (typo3/module/web/cs-seo/page-results?id=[...]) display no results when [SYS][features][security.backend.enforceContentSecurityPolicy] = true. This happens because the cs_seo JavaScripts are blocked by the TYPO3 CSP restrictions in the backend. If I set [SYS][features][security.backend.enforceContentSecurityPolicy] to "false" it works. Can you please fix this because disabling backend-CSP is not a good option for security reasons.
Tested in TYPO3 12.4.20

**Comment by mhirdes** [comment]
I merged the PR. May you can test?

**Comment by SusiSorglos** [comment]
Thanks for the patch! The result for the first level (= the selected page) is now visible. But I can't change the page-depth per selectbox to display also the results of the subpages. I think the CSP blockes the JavaScript in the onchange-attribute of the select-box: 

`<select onchange="this.form.submit();" class="form-select" id="depth" name="depth">`

It seems also that the angular.js is blocked by the CSP.

I got the following error-messages:

- Content-Security-Policy: Die Einstellungen der Seite haben die Ausführung eines JavaScript-Evals (script-src) blockiert, da es gegen folgende Direktive verstößt: "script-src 'self' 'nonce-2jsnLu51D-d6SoQ0OVqIK862US7F1j8qQKuinWAYB-LNFQ81ED3Fcw' 'report-sample'" (es fehlt 'unsafe-eval') **angular.js**:1108:7
- Content-Security-Policy: Die Einstellungen der Seite haben die Ausführung eines Event-Handlers (script-src-attr) blockiert, da es gegen folgende Direktive verstößt: "script-src 'self' 'nonce-2jsnLu51D-d6SoQ0OVqIK862US7F1j8qQKuinWAYB-LNFQ81ED3Fcw' 'report-sample'" - **Source: this.form.submit(); page-results**
- Content-Security-Policy: Die Einstellungen der Seite haben die Ausführung eines Event-Handlers (script-src-attr) blockiert, da es gegen folgende Direktive verstößt: "script-src 'self' 'nonce-2jsnLu51D-d6SoQ0OVqIK862US7F1j8qQKuinWAYB-LNFQ81ED3Fcw' 'report-sample'" - **Source: this.form.submit(); page-results**

![csp-problem](https://github.com/user-attachments/assets/da26d32b-353d-4475-b820-e467e1357c49)

Adding the onchange-function via "addEventListener" could possibly solve the problem with "this.form.submit()".

**Comment by SusiSorglos** [comment]
Sorry, I accidentally closed the issue...

**Comment by mhirdes** [comment]
Please check, should work now

**Comment by SusiSorglos** [comment]
The change of the page-depth works now. But I still get CSP errors:

![Image](https://github.com/user-attachments/assets/c101a94e-e881-47aa-b55b-b7f346952cd7)

The errors does not seem to affect the functionality of the scripts.

But I found a way to solve the problem:
If you change the Line 34 in Clickstorm\CsSeo\EventListener\PolicyMutatedEventListener from

`->extend(Directive::ScriptSrc, SourceKeyword::unsafeInline)`

to 

`->extend(Directive::ScriptSrc, SourceKeyword::unsafeInline, SourceKeyword::unsafeEval, SourceScheme::blob)`

the errors disappear.
